CREATE TABLE `t_call_log` (
  `callLogId` int(11) NOT NULL AUTO_INCREMENT,
  `phone` char(32) NOT NULL,
  `callTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`callLogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
