/*
 * This file is generated by jOOQ.
 */
package com.jooq_test.app.codegen.tables.records;


import com.jooq_test.app.codegen.tables.Country;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryRecord extends UpdatableRecordImpl<CountryRecord> implements Record3<Long, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>COUNTRY.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>COUNTRY.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>COUNTRY.MAN_COUNT</code>.
     */
    public void setManCount(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>COUNTRY.MAN_COUNT</code>.
     */
    public Integer getManCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>COUNTRY.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>COUNTRY.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Country.COUNTRY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Country.COUNTRY.MAN_COUNT;
    }

    @Override
    public Field<String> field3() {
        return Country.COUNTRY.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getManCount();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getManCount();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public CountryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CountryRecord value2(Integer value) {
        setManCount(value);
        return this;
    }

    @Override
    public CountryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CountryRecord values(Long value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryRecord
     */
    public CountryRecord() {
        super(Country.COUNTRY);
    }

    /**
     * Create a detached, initialised CountryRecord
     */
    public CountryRecord(Long id, Integer manCount, String name) {
        super(Country.COUNTRY);

        setId(id);
        setManCount(manCount);
        setName(name);
    }
}
