CREATE TABLE `t_content_activity_component` (
  `contentActivityComponentId` int(11) NOT NULL AUTO_INCREMENT,
  `activityContentId` int(11) NOT NULL,
  `joinContentId` int(11) NOT NULL,
  `clientId` int(11) NOT NULL,
  `normalVoteNum` int(11) NOT NULL,
  `expertVoteNum` int(11) NOT NULL,
  `voteNum` int(11) NOT NULL,
  `voteRank` int(11) NOT NULL,
  `voteRankDistance` int(11) NOT NULL,
  `luckyNum` int(11) NOT NULL,
  `tip` varchar(256) NOT NULL,
  `isShowTip` int(11) NOT NULL,
  `floorNum` int(11) NOT NULL,
  `point` int(11) NOT NULL,
  `pointModifyTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`contentActivityComponentId`),
  KEY `activityContentIdIndex` (`activityContentId`,`floorNum`,`createTime`),
  KEY `activityClientContentIdIndex` (`activityContentId`,`clientId`,`floorNum`,`createTime`),
  KEY `activityVoteRankContentIdIndex` (`activityContentId`,`voteRank`),
  KEY `activityJoinContentIdIndex` (`activityContentId`,`joinContentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
