/*
 * This file is generated by jOOQ.
 */
package com.jooq_test.app.codegen;


import com.jooq_test.app.codegen.tables.Country;
import com.jooq_test.app.codegen.tables.records.CountryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CountryRecord> CONSTRAINT_6 = Internal.createUniqueKey(Country.COUNTRY, DSL.name("CONSTRAINT_6"), new TableField[] { Country.COUNTRY.ID }, true);
}
