/*
 * This file is generated by jOOQ.
 */
package com.jooq_test.app.codegen;


import com.jooq_test.app.codegen.tables.Country;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>COUNTRY</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;
}
